- name: Ensure packages needed for nginx+php-fpm are present
  apt: name={{ item }} state=present
  with_items: "{{ php_required_system_packages|mandatory }}"

- name: Ensure that php_user exists
  user:
    name: "{{ php_user }}"
    createhome: no
    shell: /bin/bash
