- debug:
    msg: "Uninstalling the role php-fpm-nginx {{ php_base_name }}"

- name: Remove nginx config
  file:
    path: "/etc/nginx/sites-enabled/{{ php_base_name }}.conf"
    state: absent
  notify: nginx restart

- name: Remove FPM pool
  file:
    path: "{{ php_fpm_pool_conf_path }}/{{ php_pool_name }}.conf"
    state: absent
  when: php_create_pool
  notify: fpm restart

- block:
  - name: find {{ php_base_name }} nginx snippets
    find:
      paths: "/etc/nginx/snippets/"
      patterns: "php-fpm-{{ php_base_name }}.*.conf"
    register: result
  - name: Remove nginx snippets
    file:
      path: "{{ item.path }}"
      state: absent
    # default([]) is to avoid a warning when the previous task is skipped
    with_items: "{{ result.files|default([]) }}"
    notify: nginx restart
  when: php_uninstall_snippets
